# Generated by Django 5.1 on 2024-08-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_phonenumber_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('placename', models.CharField(max_length=100)),
                ('cityname', models.CharField(max_length=100)),
                ('hotelname', models.CharField(max_length=100)),
            ],
        ),
    ]
