# Generated by Django 5.1 on 2024-08-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urcity', models.CharField(max_length=789)),
                ('todest', models.CharField(max_length=122)),
                ('day', models.CharField(max_length=122)),
                ('seats', models.CharField(max_length=122)),
                ('message', models.TextField()),
            ],
        ),
    ]
